<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mog</string>
	</array>
	<key>name</key>
	<string>IPS-Pkg-mog</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^&lt;</string>
			<key>comment</key>
			<string>package-level metadata</string>
			<key>end</key>
			<string>&gt;$</string>
			<key>name</key>
			<string>transform.markup.text.ipspkgmog</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.text.ipspkgmog</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant.text.ipspkgmog</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(transform|include)\s+(link|hardlink|pkg)?</string>
					<key>name</key>
					<string>transform.markup.text.ipspkgmog</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(dir|file)\s+(path)(=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.constant.text.ipspkgmog</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.text.ipspkgmog</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.text.ipspkgmog</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>dir and file paths which can use regex</string>
					<key>end</key>
					<string>-&gt;</string>
					<key>name</key>
					<string>transform.path.markup.text.ipspkgmog</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.regexp</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\b(add|edit|default|delete|drop|emit|exit|print|set)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.text.ipspkgmog</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;$</string>
					<key>name</key>
					<string>modify.command.text.ipspkgmog</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(owner|group|mode|disable_fmri|enable_fmri|restart_fmri|depend)\s+</string>
							<key>name</key>
							<string>storage.type.text.ipspkgmog</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\d+\b</string>
							<key>name</key>
							<string>constant.numeric.text.ipspkgmog</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\b(svc:)[\w:/-]+</string>
							<key>name</key>
							<string>constant.numeric.text.ipspkgmog</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.ipspkg</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.regexp</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.text.ipspkgmog</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.text.ipspkgmog</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>attributes that modify actions</string>
					<key>match</key>
					<string>\b([a-z\.]+)(?==)</string>
					<key>name</key>
					<string>attribute.action.text.ipspkgmog</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.text.ipspkgmog</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.character.text.ipspkgmog</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>the values of attributes that modify actions</string>
					<key>match</key>
					<string>(=)([A-Za-z0-9_\.\/,-\?\*]+)\b</string>
					<key>name</key>
					<string>attribute.value.text.ipspkgmog</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.ipspkg</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.ipspkgmog</string>
	<key>uuid</key>
	<string>0db0f988-7455-467a-b86b-89236e410d43</string>
</dict>
</plist>
